(function(){
const allSubjects=["Mathematics","Mathematical Literacy","Physical Sciences","Life Sciences","Accounting","Business Studies","Economics","Geography","History","Tourism","Computer Applications Technology","Visual Arts","Electrical Technology","Mechanical Technology","Agricultural Sciences","English","IsiZulu","Afrikaans","Sesotho","Life Orientation"];
const provinces={"Gauteng":{"universities":[{"name":"University of Pretoria","fee":300},{"name":"Wits University","fee":100},{"name":"UJ","fee":0},{"name":"UNISA","fee":0}],"tvets":["Central Johannesburg TVET","Tshwane South TVET"]},"KwaZulu-Natal":{"universities":[{"name":"UKZN","fee":250},{"name":"DUT","fee":250},{"name":"MUT","fee":250}],"tvets":["Coastal KZN TVET","Elangeni TVET"]},"Western Cape":{"universities":[{"name":"UCT","fee":125},{"name":"Stellenbosch","fee":120},{"name":"UWC","fee":100}],"tvets":["College of Cape Town","False Bay TVET"]}};

function calculateAPS(m){return m>=80?7:m>=70?6:m>=60?5:m>=50?4:m>=40?3:m>=30?2:0;}
function buildSubjects(c=7){const b=document.getElementById("subjectsContainer");b.innerHTML="";for(let i=0;i<c;i++)addSubject();}
function addSubject(){const d=document.createElement("div");d.innerHTML='<select class="subjectSelect"><option value="">Add Subject</option>'+allSubjects.map(s=>`<option>${s}</option>`).join("")+'</select><input type="number" min="0" max="100" class="markInput" placeholder="Mark">';d.querySelector(".markInput").addEventListener("input",updateAPS);document.getElementById("subjectsContainer").appendChild(d);}
function updateAPS(){let t=0;document.querySelectorAll(".markInput").forEach(i=>t+=calculateAPS(parseInt(i.value)||0));document.getElementById("totalAps").textContent=t;}
function buildUniversities(){const c=document.getElementById("universitiesList");c.innerHTML="";for(const p in provinces){c.innerHTML+=`<div class="province-title">${p}</div><div class="province-container"><div class="institution-column"><h4>Universities</h4>${provinces[p].universities.map(u=>`<label><input type="checkbox" class="uniCheckbox" data-fee="${u.fee}" value="${u.name}">${u.name} (R${u.fee})</label>`).join("")}</div><div class="institution-column"><h4>TVET Colleges</h4>${provinces[p].tvets.map(t=>`<label><input type="checkbox" class="uniCheckbox" data-fee="0" value="${t}">${t}</label>`).join("")}</div></div>`;}c.addEventListener("change",updateFee);}
function updateFee(){let s=0;document.querySelectorAll(".uniCheckbox:checked").forEach(c=>s+=parseFloat(c.dataset.fee));document.getElementById("totalFee").textContent=s;}
function nextStep(s){document.querySelectorAll(".step").forEach(e=>e.style.display="none");document.getElementById(`step${s}`).style.display="block";}
function prevStep(s){nextStep(s);}
window.onload=()=>{buildSubjects();buildUniversities();nextStep(1);}
document.getElementById("submitApplicationBtn").onclick=()=>{const e=document.getElementById("errorMsg");e.textContent="";const n=document.getElementById("fullName").value.trim(),c=document.getElementById("contact").value.trim(),r=document.getElementById("resultsSelect").value,f=document.getElementById("nsfasSelect").value,s=document.querySelectorAll(".subjectSelect"),m=document.querySelectorAll(".markInput");if(!r){e.textContent="Select results type.";nextStep(2);return;}if(s.length<7){e.textContent="Min 7 subjects required.";nextStep(2);return;}let subM=[],v=true;for(let i=0;i<s.length;i++){if(!s[i].value||!m[i].value){v=false;break;}subM.push(`${s[i].value}: ${m[i].value}`);}if(!v){e.textContent="Complete all subjects.";nextStep(2);return;}const sel=[...document.querySelectorAll(".uniCheckbox:checked")].map(c=>c.value);if(sel.length===0){e.textContent="Select institution.";nextStep(3);return;}if(!f){e.textContent="Select NSFAS.";nextStep(3);return;}const msg=`SA Application:\nName: ${n}\nWhatsApp: ${c}\nResults: ${r}\nAPS: ${document.getElementById("totalAps").textContent}\nSubjects:\n${subM.join("\n")}\nInstitutions: ${sel.join(", ")}\nTotal Fees: R${document.getElementById("totalFee").textContent}\nNSFAS: ${f}`;window.open(`https://wa.me/27683683912?text=${encodeURIComponent(msg)}`,"_blank");}
})();