const provinces = {"Gauteng":[{"name":"University of Pretoria","fee":300},{"name":"University of Johannesburg","fee":0},{"name":"Wits University","fee":100}]};
function addSubject(){const e=document.getElementById("subjectsContainer"),t=document.createElement("div");t.className="row g-2",t.innerHTML='<div class="col-md-6"><input type="text" class="form-control mb-2" placeholder="Subject"></div><div class="col-md-6"><input type="number" class="form-control mb-2" placeholder="Mark"></div>',e.appendChild(t)}
function calculateAPS(e){return e>=80?7:e>=70?6:e>=60?5:e>=50?4:e>=40?3:e>=30?2:0}
function updateAPS(){let e=document.querySelectorAll("#subjectsContainer input[type=number]"),t=0;e.forEach(e=>{t+=calculateAPS(parseInt(e.value)||0)}),document.getElementById("totalAps").textContent=t}
function filterInstitutions(){const e=document.getElementById("searchBar").value.toLowerCase();document.querySelectorAll(".province-title").forEach(t=>{const n=t.closest(".col-12"),c=n.innerText.toLowerCase().includes(e);n.style.display=c?"block":"none"})}
function buildInstitutions(){const e=document.getElementById("institutionsContainer");e.innerHTML="";for(let t in provinces){const n=document.createElement("div");n.className="col-12",n.innerHTML=`<div class='province-title'>${t}</div>`,provinces[t].forEach(e=>{n.innerHTML+=`<div class='form-check'><input type='checkbox' class='form-check-input university' data-fee='${e.fee}' value='${e.name}'><label class='form-check-label'>${e.name} (R${e.fee})</label></div>`}),e.appendChild(n)}document.querySelectorAll(".university").forEach(e=>{e.addEventListener("change",updateTotalFee)})}
function updateTotalFee(){const e=Array.from(document.querySelectorAll(".university:checked")),t=e.reduce((e,t)=>e+parseFloat(t.dataset.fee),0);document.getElementById("totalFee").textContent=t}
function submitApplication(){const e=document.getElementById("fullName").value.trim(),t=document.getElementById("contactNumber").value.trim(),n=document.getElementById("resultsType").value,c=document.getElementById("nsfasSelect").value,o=document.getElementById("totalAps").textContent,i=Array.from(document.querySelectorAll(".university:checked")),a=i.map(e=>e.value),d=i.reduce((e,t)=>e+parseFloat(t.dataset.fee),0);if(!e||!t||!n||!a.length||!c)return void alert("Please complete all fields before submitting.");const s=`Name: ${e}\nWhatsApp: ${t}\nResults: ${n}\nAPS: ${o}\nInstitutions: ${a.join(", ")}\nFees: R${d}\nNSFAS: ${c}`;window.open(`https://wa.me/27683683912?text=${encodeURIComponent(s)}`,"_blank")}
function initPage(){alert("To process your application, you must pay R80."),buildInstitutions(),document.getElementById("subjectsContainer").addEventListener("input",updateAPS)}
